
CREATE TABLE "public"."album" (
                                  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  "imagen" text NOT NULL,
                                  "titulo" character varying(50) NOT NULL,
                                  CONSTRAINT "album_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "public"."artista" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "nombre" character varying(100) NOT NULL,
                                    CONSTRAINT "artista_pkey" PRIMARY KEY ("id"),
                                    CONSTRAINT "uk7ptc116swarkeb8akjo5tdm2l" UNIQUE ("nombre")
);

CREATE TABLE "public"."estilo" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "nombre" character varying(50) NOT NULL,
                                   CONSTRAINT "estilo_pkey" PRIMARY KEY ("id"),
                                   CONSTRAINT "uks9715gxyjqbhndfjdmp7va05u" UNIQUE ("nombre")
);

CREATE TABLE "public"."usuario" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "apellidos" character varying(100) NOT NULL,
                                    "email" character varying(100) NOT NULL,
                                    "nombre" character varying(50) NOT NULL,
                                    "password" character varying(255) NOT NULL,
                                    "rol" character varying(255) NOT NULL,
                                    "username" character varying(50) NOT NULL,
                                    CONSTRAINT "uk5171l57faosmj8myawaucatdw" UNIQUE ("email"),
                                    CONSTRAINT "uk863n1y3x0jalatoir4325ehal" UNIQUE ("username"),
                                    CONSTRAINT "usuario_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "public"."cancion" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "duracion_segundos" bigint NOT NULL,
                                    "fecha" date NOT NULL,
                                    "reproducciones" bigint NOT NULL,
                                    "titulo" character varying(100) NOT NULL,
                                    "id_album" bigint NOT NULL,
                                    "id_artista" bigint NOT NULL,
                                    "id_estilo" bigint NOT NULL,
                                    CONSTRAINT "cancion_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "public"."reproduccion" (
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         "fecha" timestamp(6) NOT NULL,
                                         "id_cancion" bigint NOT NULL,
                                         "id_usuario" bigint NOT NULL,
                                         CONSTRAINT "reproduccion_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "public"."valoracion" (
                                       "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       "valoracion" double precision NOT NULL,
                                       "id_cancion" bigint NOT NULL,
                                       "id_usuario" bigint NOT NULL,
                                       CONSTRAINT "uko7fyrjkn85t8135qqjupepjmg" UNIQUE ("id_cancion", "id_usuario"),
                                       CONSTRAINT "valoracion_pkey" PRIMARY KEY ("id")
);

-- Foreign Keys
ALTER TABLE ONLY "public"."cancion" ADD CONSTRAINT "fk3tnedvv10ost7ywit7y572b1e" FOREIGN KEY (id_album) REFERENCES album(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."cancion" ADD CONSTRAINT "fk7o3hjn3jt230ojsygc6drl5fs" FOREIGN KEY (id_artista) REFERENCES artista(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."cancion" ADD CONSTRAINT "fkhffp7xx338sp6s9r9mqo0iffx" FOREIGN KEY (id_estilo) REFERENCES estilo(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."reproduccion" ADD CONSTRAINT "fk2tx3rvjsjl2rnh00vi13uhovb" FOREIGN KEY (id_cancion) REFERENCES cancion(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."reproduccion" ADD CONSTRAINT "fk9v7yxujm57ubq5po9qbghu90b" FOREIGN KEY (id_usuario) REFERENCES usuario(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."valoracion" ADD CONSTRAINT "fkff3i9suewew2gicui3qsllakw" FOREIGN KEY (id_cancion) REFERENCES cancion(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."valoracion" ADD CONSTRAINT "fkkf165idseexrg1k9o7fqusoey" FOREIGN KEY (id_usuario) REFERENCES usuario(id) NOT DEFERRABLE;